updated ci/cd file

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -63,10 +63,11 @@ jobs:
 
       - name: Lint SQL Files
         run: |
-          sql-lint src/main/resources/db/**/*.sql || exit_code=$?
-          if [ $exit_code -ne 0 ]; then
+          OUTPUT=$(sql-lint src/main/resources/db/**/*.sql || true)
+          echo "$OUTPUT"
+          if echo "$OUTPUT" | grep -q "Unable to lint"; then
             echo "SQL Linting failed. Stopping the build."
-            exit $exit_code
+            exit 1
           fi
         id: lint_sql
 
