updated ci/cd file

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -63,8 +63,11 @@ jobs:
 
       - name: Lint SQL Files
         run: |
-          sql-lint src/main/resources/db/**/*.sql
-        continue-on-error: false
+          sql-lint src/main/resources/db/**/*.sql || exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "SQL Linting failed. Stopping the build."
+            exit $exit_code
+          fi
         id: lint_sql
 
       - name: Build Application
