updated ci/cd file

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -63,8 +63,14 @@ jobs:
 
       - name: Lint SQL Files
         run: |
-          sql-lint src/main/resources/db/**/*.sql
-      
+          OUTPUT=$(sql-lint src/main/resources/db/**/*.sql || true)
+          echo "$OUTPUT"
+          if echo "$OUTPUT" | grep -q "Unable to lint"; then
+            echo "SQL Linting failed. Stopping the build."
+            exit 1
+          fi
+        id: lint_sql
+
       - name: Build Application
         run: ./gradlew clean build --info
         id: build
